
export default {

    RESPONSE_BOOKS_SUCCESS : 'RESPONSE_BOOKS_SUCCESS',
    SET_CURRENT_PAGE       : 'SET_CURRENT_PAGE',
    SET_TOTAL_BOOKS        : 'SET_TOTAL_BOOKS',
    SET_BOOKS_PER_PAGE     : 'SET_BOOKS_PER_PAGE',
    SET_EDITABLE_ITEM      : 'SET_EDITABLE_ITEM',
    RESET_EDITABLE_ITEM    : 'RESET_EDITABLE_ITEM',
    CHANGE_TITLE           : 'CHANGE_TITLE',
    CHANGE_DATE            : 'CHANGE_DATE',
    CHANGE_DESCRIPTION     : 'CHANGE_DESCRIPTION',
    CHANGE_AUTHOR          : 'CHANGE_AUTHOR',
    CHANGE_IMAGE           : 'CHANGE_IMAGE',
};
